# -*- coding: utf-8 -*-
"""assignment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geuD_d_EMNXYhWYkyzEU53YOhWKPlDjn
"""

pip install seaborn

import seaborn as sns

print(sns.get_dataset_names())

df=sns.load_dataset('car_crashes')

df

df.info()

df.head(6)

sns.scatterplot(x="alcohol",y="speeding",data=df)

sns.distplot(df['total'])

sns.barplot(x='total',y= 'abbrev',data=df,orient='h')

sns.jointplot(x='total',y='alcohol',data=df)

sns.lineplot(y="alcohol",x="speeding",data=df,ci=None)

sns.boxplot(x="total",y="not_distracted",data=df)

sns.countplot(x="no_previous",data=df)

sns.pairplot(df)